version: "2"

services:
  app:
    build:
      context: .
    container_name: challenge-app
    volumes:
      - .:/var/www:rw
    networks:
      - challenge-network
    env_file:
      - .env
    ports:
    - "8080:8080"

networks:
  challenge-network:
    driver: bridge
